#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := AES_Encryptor_Decryptor_ESP32

include $(IDF_PATH)/make/project.mk

